name: Update repo data
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    update-neu-data:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.BOT_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Run Script
              run: |
                  node .github/scripts/update_neu.mjs

            - name: Commit and push changes
              continue-on-error: true
              run: |
                  git config --global user.email "meowtomation@users.noreply.github.com"
                  git config --global user.name "meowtomation"
                  git add .
                  git commit -m "Update Repository"
                  git push
